[Task][58751] Create UI ImageScreen
awesome-academy/wallpaper pull request #5
Opened 2023-01-10 05:08 UTC by thaidd-1309

## Related Tickets
- [#Task 58751: Content](https://edu-redmine.sun-asterisk.vn/issues/58751)
## WHAT
-Create UI
-Create Reusecell
-Custom TabBar
## Evidence (Screenshot or Video)
![Simulator Screen Shot - iPhone 13 - 2023-01-10 at 12 06 34](https://user-images.githubusercontent.com/119989192/211466533-9325167e-6682-4d56-a78f-47c06fb95fb5.png)

## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*
*(Other notes)*

2023-01-10 05:48 UTC, hanh-3224 commented on WallPaper_Project1/WallPaper_Project1/AppDelegate.swift
> +
Xoá các hàm không dùng

2023-01-10 05:49 UTC, hanh-3224 commented on WallPaper_Project1/WallPaper_Project1/SceneDelegate.swift
> +    }
xoá các hàm không dùng

2023-01-10 05:50 UTC, hanh-3224 commented on WallPaper_Project1/WallPaper_Project1/Scenes/ImageScreen/ImageViewController.swift
class này dùng làm gì thế em

2023-01-10 05:54 UTC, hanh-3224 commented on WallPaper_Project1/WallPaper_Project1/ViewController.swift
> +}
file này không dùng thì xoá đi e nhé

2023-01-10 05:55 UTC, tunghs-1253 commented on WallPaper_Project1/WallPaper_Project1/Widgets/ImageCell/ImageCollectionViewCell.swift
> +class ImageCollectionViewCell: UICollectionViewCell, ReuseCell {
Thái hay quên final thế nhỉ ^^ Tương tự với các class phía trên nhé Thái

2023-01-10 05:56 UTC, hanh-3224 commented on WallPaper_Project1/WallPaper_Project1/Widgets/CategoryCell/CategoryCollectionViewCell.swift
> +    override func awakeFromNib() {
cách dòng

2023-01-10 05:56 UTC, hanh-3224 commented on WallPaper_Project1/WallPaper_Project1/Scenes/ImageScreen/ImageViewController.swift
>          super.viewDidLoad()
Cách dòng

2023-01-10 06:07 UTC, thaidd-1309 commented on WallPaper_Project1/WallPaper_Project1/Scenes/ImageScreen/ImageViewController.swift
Dùng để control ImageScreen ạ

2023-01-10 06:24 UTC, thuannv-2723 commented on WallPaper_Project1/WallPaper_Project1/Scenes/ImageScreen/ImageViewController.swift
> +        self.categoryCollectionView.layer.cornerRadius = categoryCollectionView.frame.height / 2
Không dùng self. trên VC thế này em. Dễ ăn RC lắm

2023-01-10 06:24 UTC, thuannv-2723 commented on WallPaper_Project1/WallPaper_Project1/Scenes/ImageScreen/ImageViewController.swift
> +    }
Same

2023-01-10 06:27 UTC, thuannv-2723 commented on WallPaper_Project1/WallPaper_Project1/Scenes/ImageScreen/ImageViewController.swift
> +        if collectionView == self.categoryCollectionView {
bỏ self em ơi

2023-01-10 06:27 UTC, thuannv-2723 commented on WallPaper_Project1/WallPaper_Project1/Scenes/ImageScreen/ImageViewController.swift
> +        }
hardcode thì comment vào em nhé

2023-01-10 06:27 UTC, thuannv-2723 commented on WallPaper_Project1/WallPaper_Project1/Scenes/MainTabBar/TabBarViewController.swift
>      }
bỏ hết self. em nhé

2023-01-10 06:29 UTC, thuannv-2723 commented on WallPaper_Project1/WallPaper_Project1/Widgets/ImageCell/ImageCollectionViewCell.swift
> +        self.layer.cornerRadius = 12
same

2023-01-10 06:29 UTC, thuannv-2723 commented on WallPaper_Project1/WallPaper_Project1/Scenes/MainTabBar/TabBarViewController.swift
> +        self.drawLayerTabBar()
same

2023-01-10 06:31 UTC, thuannv-2723 commented on WallPaper_Project1/WallPaper_Project1/Scenes/ImageScreen/ImageViewController.swift
> +            return cell
sử dụng dequeueReusableCell(withReuseIdentifier:for:)

2023-01-10 10:06 UTC, thuannv-2723 requested changes

2023-01-10 10:06 UTC, thuannv-2723 commented on WallPaper_Project1/WallPaper_Project1/Scenes/MainTabBar/TabBarViewController.swift
>          for index in 0..<items.count {
ForEarch

2023-01-10 10:06 UTC, thuannv-2723 commented on WallPaper_Project1/WallPaper_Project1/Scenes/MainTabBar/TabBarViewController.swift
> +        guard let items = tabBar.items else {return}
Convention em

2023-01-10 10:06 UTC, thuannv-2723 commented on WallPaper_Project1/WallPaper_Project1/Scenes/MainTabBar/TabBarViewController.swift
> +        let roundRect = CGRect(x: 40, y: tabBar.bounds.minY,
Convention

2023-01-10 12:51 UTC, phonglh-2668 commented on WallPaper_Project1/WallPaper_Project1/AppDelegate.swift
> +    }
remove đi hết đống này đi e

2023-01-10 12:51 UTC, phonglh-2668 commented on WallPaper_Project1/WallPaper_Project1/SceneDelegate.swift
> +class SceneDelegate: UIResponder, UIWindowSceneDelegate {
xoá luôn file này lun e

2023-01-10 12:51 UTC, phonglh-2668 commented on WallPaper_Project1/WallPaper_Project1/Scenes/ImageScreen/ImageViewController.swift
> +        categoryCollectionView.register(nibName: CategoryCollectionViewCell.self )
```suggestion
        categoryCollectionView.register(nibName: CategoryCollectionViewCell.self)
```

2023-01-10 12:51 UTC, phonglh-2668 commented on WallPaper_Project1/WallPaper_Project1/Scenes/ImageScreen/ImageViewController.swift
> +        }
```suggestion
       return collectionView == categoryCollectionView ? 10 : 20
```

2023-01-10 12:51 UTC, phonglh-2668 commented on WallPaper_Project1/WallPaper_Project1/Scenes/MainTabBar/TabBarViewController.swift
> +        layer.path = UIBezierPath(roundedRect: roundRect, cornerRadius: (tabBar.frame.width/2)).cgPath
```suggestion
        layer.path = UIBezierPath(roundedRect: roundRect, cornerRadius: (tabBar.frame.width / 2)).cgPath
```

2023-01-10 12:51 UTC, phonglh-2668 commented on WallPaper_Project1/WallPaper_Project1/Widgets/CategoryCell/CategoryCollectionViewCell.swift
> +    @IBOutlet private weak var categoryName: UILabel!
```suggestion
    @IBOutlet private weak var categoryNameLabel: UILabel!
```

2023-01-10 12:51 UTC, phonglh-2668 commented on WallPaper_Project1/WallPaper_Project1/Widgets/ImageCell/ImageCollectionViewCell.swift
> +
thêm prepareForReuse cho thằng imageView lun e

2023-01-10 14:04 UTC, thaidd-1309 commented on WallPaper_Project1/WallPaper_Project1/SceneDelegate.swift
> +class SceneDelegate: UIResponder, UIWindowSceneDelegate {
Em xoá file này thì ko chạy vào được màn hình chính. E xoá file AppDelegate thì vẫn chạy bình thường. Hay do e sai ở đâu a nhỉ

2023-01-11 01:08 UTC, tuta-3205 commented on WallPaper_Project1/WallPaper_Project1/SceneDelegate.swift
> +class SceneDelegate: UIResponder, UIWindowSceneDelegate {
@thaidd-1309 :v xóa xong fix đi bro, 1 hồi là nó chạy được

2023-01-11 01:30 UTC, thaidd-1309 commented on WallPaper_Project1/WallPaper_Project1/SceneDelegate.swift
> +class SceneDelegate: UIResponder, UIWindowSceneDelegate {
@tuta-3205 , mình fix dc rồi nhé

2023-01-11 03:00 UTC, merged